version: '3.8'
services:
  flask-api:
    container_name: flask_api
    env_file: ./backend/.env
    build:
      target: backend
    volumes:
      - ./backend:/app
    ports:
      - 5000:5000
    stdin_open: true
    tty: true
  
  react-ui:
    container_name: react-ui
    build:
      target: frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true