version: '3.8'
      
networks:
  db_network:
    driver: bridge'
  web_network:
    driver: bridge

services:
  flask-api:
    container_name: flask-api
    env_file: ./backend/.env
    build:
      target: backend
    volumes:
      - ./backend:/app
    networks:
      - web_network
    ports: 
      - 5000:5000
    stdin_open: true
    tty: true

  
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5000:5000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - flask-api


  react-ui:
    container_name: react-ui
    build:
      target: frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
